version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-container
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - spring-boot-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-api-authentication-container
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - spring-boot-network


networks:
  spring-boot-network:
    driver: bridge

volumes:
  postgres-data:
